//go:build linux && (amd64 || arm64)

package fsys

import "syscall"

// errnoName names each linux errno, or returns "". The syscall constants
// carry this platform's numbers. Only the supported architectures build it:
// numbers differ elsewhere (on mips, 133 is EISCONN and EDEADLOCK has its
// own number), so a build on another linux architecture fails for want of
// errnoName rather than misnaming. The compiler refuses two cases with one
// number, so each alias appears once, under its canonical name.
func errnoName(e syscall.Errno) string {
	switch e {
	case syscall.EPERM:
		return "EPERM"
	case syscall.ENOENT:
		return "ENOENT"
	case syscall.ESRCH:
		return "ESRCH"
	case syscall.EINTR:
		return "EINTR"
	case syscall.EIO:
		return "EIO"
	case syscall.ENXIO:
		return "ENXIO"
	case syscall.E2BIG:
		return "E2BIG"
	case syscall.ENOEXEC:
		return "ENOEXEC"
	case syscall.EBADF:
		return "EBADF"
	case syscall.ECHILD:
		return "ECHILD"
	case syscall.EAGAIN:
		return "EAGAIN"
	case syscall.ENOMEM:
		return "ENOMEM"
	case syscall.EACCES:
		return "EACCES"
	case syscall.EFAULT:
		return "EFAULT"
	case syscall.ENOTBLK:
		return "ENOTBLK"
	case syscall.EBUSY:
		return "EBUSY"
	case syscall.EEXIST:
		return "EEXIST"
	case syscall.EXDEV:
		return "EXDEV"
	case syscall.ENODEV:
		return "ENODEV"
	case syscall.ENOTDIR:
		return "ENOTDIR"
	case syscall.EISDIR:
		return "EISDIR"
	case syscall.EINVAL:
		return "EINVAL"
	case syscall.ENFILE:
		return "ENFILE"
	case syscall.EMFILE:
		return "EMFILE"
	case syscall.ENOTTY:
		return "ENOTTY"
	case syscall.ETXTBSY:
		return "ETXTBSY"
	case syscall.EFBIG:
		return "EFBIG"
	case syscall.ENOSPC:
		return "ENOSPC"
	case syscall.ESPIPE:
		return "ESPIPE"
	case syscall.EROFS:
		return "EROFS"
	case syscall.EMLINK:
		return "EMLINK"
	case syscall.EPIPE:
		return "EPIPE"
	case syscall.EDOM:
		return "EDOM"
	case syscall.ERANGE:
		return "ERANGE"
	case syscall.EDEADLK:
		return "EDEADLK"
	case syscall.ENAMETOOLONG:
		return "ENAMETOOLONG"
	case syscall.ENOLCK:
		return "ENOLCK"
	case syscall.ENOSYS:
		return "ENOSYS"
	case syscall.ENOTEMPTY:
		return "ENOTEMPTY"
	case syscall.ELOOP:
		return "ELOOP"
	case syscall.ENOMSG:
		return "ENOMSG"
	case syscall.EIDRM:
		return "EIDRM"
	case syscall.ECHRNG:
		return "ECHRNG"
	case syscall.EL2NSYNC:
		return "EL2NSYNC"
	case syscall.EL3HLT:
		return "EL3HLT"
	case syscall.EL3RST:
		return "EL3RST"
	case syscall.ELNRNG:
		return "ELNRNG"
	case syscall.EUNATCH:
		return "EUNATCH"
	case syscall.ENOCSI:
		return "ENOCSI"
	case syscall.EL2HLT:
		return "EL2HLT"
	case syscall.EBADE:
		return "EBADE"
	case syscall.EBADR:
		return "EBADR"
	case syscall.EXFULL:
		return "EXFULL"
	case syscall.ENOANO:
		return "ENOANO"
	case syscall.EBADRQC:
		return "EBADRQC"
	case syscall.EBADSLT:
		return "EBADSLT"
	case syscall.EBFONT:
		return "EBFONT"
	case syscall.ENOSTR:
		return "ENOSTR"
	case syscall.ENODATA:
		return "ENODATA"
	case syscall.ETIME:
		return "ETIME"
	case syscall.ENOSR:
		return "ENOSR"
	case syscall.ENONET:
		return "ENONET"
	case syscall.ENOPKG:
		return "ENOPKG"
	case syscall.EREMOTE:
		return "EREMOTE"
	case syscall.ENOLINK:
		return "ENOLINK"
	case syscall.EADV:
		return "EADV"
	case syscall.ESRMNT:
		return "ESRMNT"
	case syscall.ECOMM:
		return "ECOMM"
	case syscall.EPROTO:
		return "EPROTO"
	case syscall.EMULTIHOP:
		return "EMULTIHOP"
	case syscall.EDOTDOT:
		return "EDOTDOT"
	case syscall.EBADMSG:
		return "EBADMSG"
	case syscall.EOVERFLOW:
		return "EOVERFLOW"
	case syscall.ENOTUNIQ:
		return "ENOTUNIQ"
	case syscall.EBADFD:
		return "EBADFD"
	case syscall.EREMCHG:
		return "EREMCHG"
	case syscall.ELIBACC:
		return "ELIBACC"
	case syscall.ELIBBAD:
		return "ELIBBAD"
	case syscall.ELIBSCN:
		return "ELIBSCN"
	case syscall.ELIBMAX:
		return "ELIBMAX"
	case syscall.ELIBEXEC:
		return "ELIBEXEC"
	case syscall.EILSEQ:
		return "EILSEQ"
	case syscall.ERESTART:
		return "ERESTART"
	case syscall.ESTRPIPE:
		return "ESTRPIPE"
	case syscall.EUSERS:
		return "EUSERS"
	case syscall.ENOTSOCK:
		return "ENOTSOCK"
	case syscall.EDESTADDRREQ:
		return "EDESTADDRREQ"
	case syscall.EMSGSIZE:
		return "EMSGSIZE"
	case syscall.EPROTOTYPE:
		return "EPROTOTYPE"
	case syscall.ENOPROTOOPT:
		return "ENOPROTOOPT"
	case syscall.EPROTONOSUPPORT:
		return "EPROTONOSUPPORT"
	case syscall.ESOCKTNOSUPPORT:
		return "ESOCKTNOSUPPORT"
	case syscall.ENOTSUP:
		return "ENOTSUP"
	case syscall.EPFNOSUPPORT:
		return "EPFNOSUPPORT"
	case syscall.EAFNOSUPPORT:
		return "EAFNOSUPPORT"
	case syscall.EADDRINUSE:
		return "EADDRINUSE"
	case syscall.EADDRNOTAVAIL:
		return "EADDRNOTAVAIL"
	case syscall.ENETDOWN:
		return "ENETDOWN"
	case syscall.ENETUNREACH:
		return "ENETUNREACH"
	case syscall.ENETRESET:
		return "ENETRESET"
	case syscall.ECONNABORTED:
		return "ECONNABORTED"
	case syscall.ECONNRESET:
		return "ECONNRESET"
	case syscall.ENOBUFS:
		return "ENOBUFS"
	case syscall.EISCONN:
		return "EISCONN"
	case syscall.ENOTCONN:
		return "ENOTCONN"
	case syscall.ESHUTDOWN:
		return "ESHUTDOWN"
	case syscall.ETOOMANYREFS:
		return "ETOOMANYREFS"
	case syscall.ETIMEDOUT:
		return "ETIMEDOUT"
	case syscall.ECONNREFUSED:
		return "ECONNREFUSED"
	case syscall.EHOSTDOWN:
		return "EHOSTDOWN"
	case syscall.EHOSTUNREACH:
		return "EHOSTUNREACH"
	case syscall.EALREADY:
		return "EALREADY"
	case syscall.EINPROGRESS:
		return "EINPROGRESS"
	case syscall.ESTALE:
		return "ESTALE"
	case syscall.EUCLEAN:
		return "EUCLEAN"
	case syscall.ENOTNAM:
		return "ENOTNAM"
	case syscall.ENAVAIL:
		return "ENAVAIL"
	case syscall.EISNAM:
		return "EISNAM"
	case syscall.EREMOTEIO:
		return "EREMOTEIO"
	case syscall.EDQUOT:
		return "EDQUOT"
	case syscall.ENOMEDIUM:
		return "ENOMEDIUM"
	case syscall.EMEDIUMTYPE:
		return "EMEDIUMTYPE"
	case syscall.ECANCELED:
		return "ECANCELED"
	case syscall.ENOKEY:
		return "ENOKEY"
	case syscall.EKEYEXPIRED:
		return "EKEYEXPIRED"
	case syscall.EKEYREVOKED:
		return "EKEYREVOKED"
	case syscall.EKEYREJECTED:
		return "EKEYREJECTED"
	case syscall.EOWNERDEAD:
		return "EOWNERDEAD"
	case syscall.ENOTRECOVERABLE:
		return "ENOTRECOVERABLE"
	case syscall.ERFKILL:
		return "ERFKILL"
	case syscall.Errno(133): // not defined by syscall on every linux architecture
		return "EHWPOISON"
	}
	return ""
}
