package fsys

import "syscall"

// errnoName names each darwin errno, or returns "". The syscall constants
// carry this platform's numbers. EOPNOTSUPP has its own number here, which
// is also named ENOTSUP. ELAST marks the end of the range and is not an
// error.
func errnoName(e syscall.Errno) string {
	switch e {
	case syscall.EPERM:
		return "EPERM"
	case syscall.ENOENT:
		return "ENOENT"
	case syscall.ESRCH:
		return "ESRCH"
	case syscall.EINTR:
		return "EINTR"
	case syscall.EIO:
		return "EIO"
	case syscall.ENXIO:
		return "ENXIO"
	case syscall.E2BIG:
		return "E2BIG"
	case syscall.ENOEXEC:
		return "ENOEXEC"
	case syscall.EBADF:
		return "EBADF"
	case syscall.ECHILD:
		return "ECHILD"
	case syscall.EDEADLK:
		return "EDEADLK"
	case syscall.ENOMEM:
		return "ENOMEM"
	case syscall.EACCES:
		return "EACCES"
	case syscall.EFAULT:
		return "EFAULT"
	case syscall.ENOTBLK:
		return "ENOTBLK"
	case syscall.EBUSY:
		return "EBUSY"
	case syscall.EEXIST:
		return "EEXIST"
	case syscall.EXDEV:
		return "EXDEV"
	case syscall.ENODEV:
		return "ENODEV"
	case syscall.ENOTDIR:
		return "ENOTDIR"
	case syscall.EISDIR:
		return "EISDIR"
	case syscall.EINVAL:
		return "EINVAL"
	case syscall.ENFILE:
		return "ENFILE"
	case syscall.EMFILE:
		return "EMFILE"
	case syscall.ENOTTY:
		return "ENOTTY"
	case syscall.ETXTBSY:
		return "ETXTBSY"
	case syscall.EFBIG:
		return "EFBIG"
	case syscall.ENOSPC:
		return "ENOSPC"
	case syscall.ESPIPE:
		return "ESPIPE"
	case syscall.EROFS:
		return "EROFS"
	case syscall.EMLINK:
		return "EMLINK"
	case syscall.EPIPE:
		return "EPIPE"
	case syscall.EDOM:
		return "EDOM"
	case syscall.ERANGE:
		return "ERANGE"
	case syscall.EAGAIN:
		return "EAGAIN"
	case syscall.EINPROGRESS:
		return "EINPROGRESS"
	case syscall.EALREADY:
		return "EALREADY"
	case syscall.ENOTSOCK:
		return "ENOTSOCK"
	case syscall.EDESTADDRREQ:
		return "EDESTADDRREQ"
	case syscall.EMSGSIZE:
		return "EMSGSIZE"
	case syscall.EPROTOTYPE:
		return "EPROTOTYPE"
	case syscall.ENOPROTOOPT:
		return "ENOPROTOOPT"
	case syscall.EPROTONOSUPPORT:
		return "EPROTONOSUPPORT"
	case syscall.ESOCKTNOSUPPORT:
		return "ESOCKTNOSUPPORT"
	case syscall.ENOTSUP:
		return "ENOTSUP"
	case syscall.EPFNOSUPPORT:
		return "EPFNOSUPPORT"
	case syscall.EAFNOSUPPORT:
		return "EAFNOSUPPORT"
	case syscall.EADDRINUSE:
		return "EADDRINUSE"
	case syscall.EADDRNOTAVAIL:
		return "EADDRNOTAVAIL"
	case syscall.ENETDOWN:
		return "ENETDOWN"
	case syscall.ENETUNREACH:
		return "ENETUNREACH"
	case syscall.ENETRESET:
		return "ENETRESET"
	case syscall.ECONNABORTED:
		return "ECONNABORTED"
	case syscall.ECONNRESET:
		return "ECONNRESET"
	case syscall.ENOBUFS:
		return "ENOBUFS"
	case syscall.EISCONN:
		return "EISCONN"
	case syscall.ENOTCONN:
		return "ENOTCONN"
	case syscall.ESHUTDOWN:
		return "ESHUTDOWN"
	case syscall.ETOOMANYREFS:
		return "ETOOMANYREFS"
	case syscall.ETIMEDOUT:
		return "ETIMEDOUT"
	case syscall.ECONNREFUSED:
		return "ECONNREFUSED"
	case syscall.ELOOP:
		return "ELOOP"
	case syscall.ENAMETOOLONG:
		return "ENAMETOOLONG"
	case syscall.EHOSTDOWN:
		return "EHOSTDOWN"
	case syscall.EHOSTUNREACH:
		return "EHOSTUNREACH"
	case syscall.ENOTEMPTY:
		return "ENOTEMPTY"
	case syscall.EPROCLIM:
		return "EPROCLIM"
	case syscall.EUSERS:
		return "EUSERS"
	case syscall.EDQUOT:
		return "EDQUOT"
	case syscall.ESTALE:
		return "ESTALE"
	case syscall.EREMOTE:
		return "EREMOTE"
	case syscall.EBADRPC:
		return "EBADRPC"
	case syscall.ERPCMISMATCH:
		return "ERPCMISMATCH"
	case syscall.EPROGUNAVAIL:
		return "EPROGUNAVAIL"
	case syscall.EPROGMISMATCH:
		return "EPROGMISMATCH"
	case syscall.EPROCUNAVAIL:
		return "EPROCUNAVAIL"
	case syscall.ENOLCK:
		return "ENOLCK"
	case syscall.ENOSYS:
		return "ENOSYS"
	case syscall.EFTYPE:
		return "EFTYPE"
	case syscall.EAUTH:
		return "EAUTH"
	case syscall.ENEEDAUTH:
		return "ENEEDAUTH"
	case syscall.EPWROFF:
		return "EPWROFF"
	case syscall.EDEVERR:
		return "EDEVERR"
	case syscall.EOVERFLOW:
		return "EOVERFLOW"
	case syscall.EBADEXEC:
		return "EBADEXEC"
	case syscall.EBADARCH:
		return "EBADARCH"
	case syscall.ESHLIBVERS:
		return "ESHLIBVERS"
	case syscall.EBADMACHO:
		return "EBADMACHO"
	case syscall.ECANCELED:
		return "ECANCELED"
	case syscall.EIDRM:
		return "EIDRM"
	case syscall.ENOMSG:
		return "ENOMSG"
	case syscall.EILSEQ:
		return "EILSEQ"
	case syscall.ENOATTR:
		return "ENOATTR"
	case syscall.EBADMSG:
		return "EBADMSG"
	case syscall.EMULTIHOP:
		return "EMULTIHOP"
	case syscall.ENODATA:
		return "ENODATA"
	case syscall.ENOLINK:
		return "ENOLINK"
	case syscall.ENOSR:
		return "ENOSR"
	case syscall.ENOSTR:
		return "ENOSTR"
	case syscall.EPROTO:
		return "EPROTO"
	case syscall.ETIME:
		return "ETIME"
	case syscall.EOPNOTSUPP:
		return "ENOTSUP"
	case syscall.ENOPOLICY:
		return "ENOPOLICY"
	case syscall.ENOTRECOVERABLE:
		return "ENOTRECOVERABLE"
	case syscall.EOWNERDEAD:
		return "EOWNERDEAD"
	case syscall.Errno(106): // not defined by syscall on every darwin architecture
		return "EQFULL"
	}
	return ""
}
